// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main(lv_event_t * e);
lv_obj_t * ui_main;
void ui_event_nextBtn1(lv_event_t * e);
lv_obj_t * ui_nextBtn1;
lv_obj_t * ui_connectionStatusLabel;
lv_obj_t * ui_connectionStatus;
lv_obj_t * ui_battery1;
lv_obj_t * ui_charge1;
// CUSTOM VARIABLES


// SCREEN: ui_solidColor
void ui_solidColor_screen_init(void);
void ui_event_solidColor(lv_event_t * e);
lv_obj_t * ui_solidColor;
void ui_event_nextBtn2(lv_event_t * e);
lv_obj_t * ui_nextBtn2;
void ui_event_redSlide(lv_event_t * e);
lv_obj_t * ui_redSlide;
void ui_event_greenSlide(lv_event_t * e);
lv_obj_t * ui_greenSlide;
void ui_event_blueSlide(lv_event_t * e);
lv_obj_t * ui_blueSlide;
lv_obj_t * ui_redLabel;
lv_obj_t * ui_greenLabel;
lv_obj_t * ui_blueLabel;
lv_obj_t * ui_battery2;
lv_obj_t * ui_charge2;
// CUSTOM VARIABLES


// SCREEN: ui_effects
void ui_effects_screen_init(void);
void ui_event_effects(lv_event_t * e);
lv_obj_t * ui_effects;
void ui_event_nextBtn3(lv_event_t * e);
lv_obj_t * ui_nextBtn3;
void ui_event_effectsRoller(lv_event_t * e);
lv_obj_t * ui_effectsRoller;
lv_obj_t * ui_battery3;
lv_obj_t * ui_charge3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_[5] = {&ui_img_0_png, &ui_img_25_png, &ui_img_50_png, &ui_img_75_png, &ui_img_100_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 8
    #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        screen_1_start_load(e);
    }
}

void ui_event_nextBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_solidColor, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_solidColor_screen_init);
    }
}

void ui_event_solidColor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        screen_2_start_load(e);
    }
}

void ui_event_nextBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_effects, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_effects_screen_init);
    }
}

void ui_event_redSlide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_redLabel, target, "R. ", "");
    }
}

void ui_event_greenSlide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_greenLabel, target, "G. ", "");
    }
}

void ui_event_blueSlide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_blueLabel, target, "B. ", "");
    }
}

void ui_event_effects(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        screen_3_start_load(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        screen_3_start_unload(e);
    }
}

void ui_event_nextBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_main_screen_init);
    }
}

void ui_event_effectsRoller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_LEFT) {
        scr3_roller_key_left(e);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        scr3_roller_key_right(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui_solidColor_screen_init();
    ui_effects_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
