// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_COMP_NEXTBTN_H
#define _UI_COMP_NEXTBTN_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT nextBtn
#define UI_COMP_NEXTBTN_NEXTBTN 0
#define _UI_COMP_NEXTBTN_NUM 1
lv_obj_t * ui_nextBtn_create(lv_obj_t * comp_parent);
void ui_event_comp_nextBtn_nextBtn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
