// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_COMP_BATTERYBAR_H
#define _UI_COMP_BATTERYBAR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT batteryBar
#define UI_COMP_BATTERYBAR_BATTERYBAR 0
#define _UI_COMP_BATTERYBAR_NUM 1
lv_obj_t * ui_batteryBar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
