// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"


void ui_event_comp_nextBtn_nextBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_nextBtn = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_RIGHT) {
        _ui_screen_change(&ui_solidColor, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_solidColor_screen_init);
    }
}

// COMPONENT nextBtn

lv_obj_t * ui_nextBtn_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_nextBtn;
    cui_nextBtn = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_nextBtn, 5);
    lv_obj_set_height(cui_nextBtn, 5);
    lv_obj_set_x(cui_nextBtn, -55);
    lv_obj_set_y(cui_nextBtn, 9);
    lv_obj_set_align(cui_nextBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_nextBtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(cui_nextBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_nextBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(cui_nextBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_opa(cui_nextBtn, 255, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_width(cui_nextBtn, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);
    lv_obj_set_style_outline_pad(cui_nextBtn, 0, LV_PART_MAIN | LV_STATE_FOCUS_KEY);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NEXTBTN_NUM);
    children[UI_COMP_NEXTBTN_NEXTBTN] = cui_nextBtn;
    lv_obj_add_event_cb(cui_nextBtn, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_nextBtn, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_nextBtn, ui_event_comp_nextBtn_nextBtn, LV_EVENT_ALL, children);
    ui_comp_nextBtn_create_hook(cui_nextBtn);
    return cui_nextBtn;
}

